### ISSUE TITLE
Pathfinder returns non-liquid paths

### ISSUE THREAD

**Issue by jaensen** [CirclesUBI/pathfinder2#4]
Hi! 

I experience a capcity-exhaustion bug when calculating transitive transfers between me and Martin. The path routes from me via two organizations to Martin. When my direct send limit is exhausted, the pathfinder tries to find more capacity via the two orgas and uses them for a transitive transfer. In the following transfers from the orgas to Martin it exceeds the capacity limits of the hub's 'checkSendLimit()' function.  

Also the pathfinder adds steps that enter and exit with the same amount of the same tokens (see "Alte Utting". E.g. 100 Daniel CRC in, 100 Daniel CRC out) which shouldn't have any influence on the actual send limits!?

I added a quick recap of 'checkSendLimit()' and the described example flow below.

## checkSendLimit()
A function that's implemented in the Circles Hub-Contract. Is used to determine the max. amount of Circles one user can send to another.  

Depends on ..
1) The sender's balance of the transacted token (`srcBalance`)  
   _This value is only important if the receiver is the owner of the transacted token or is an organization. In both cases the receiver then accepts all trusted CRC._
2) The receiver's balance of the transacted token (`destBalance`)
   _The more tokens of the transacted type are already held by the receiver, the smaller the further amount that can be sent to him._
3) The receiver's balance of his/her own token (`destsOwnTokenHolding`)  
   _The fewer own tokens a receiver holds, the less other tokens he can receive._
4) The receiver's trust limit for the sender (`limit`)  
   _More trust = More liquidity_

The function behaves differently depending on whether receiver is an organization or a person. Organizations don't have a limit for receiving trusted tokens.  Also every token owner accepts all incoming own tokens.

### Formulas:
The original solidity code is as following:
```solidity
uint256 srcBalance = userToToken[tokenOwner].balanceOf(src);
if (tokenOwner == dest || organizations[dest]) {
    return srcBalance;
}
uint256 destBalance = userToToken[tokenOwner].balanceOf(dest);
uint256 max = (userToToken[dest].balanceOf(dest).mul(limits[dest][tokenOwner])).div(oneHundred);
if (max < destBalance) return 0;
uint256 destBalanceScaled = destBalance.mul(oneHundred.sub(limits[dest][tokenOwner])).div(oneHundred);
return max.sub(destBalanceScaled);
```
To calculate the max flow to an individual we only need these formulas:
* max := destsOwnTokenHolding * limit / 100  
* destBalanceScaled := destBalance * (100 - limit) / 100  
* capacity := max - destBalanceScaled  

### Example
The example is taken from a real pathfinder response and corresponds with the attached flow-graph. In it 'Daniel' wants to send various CRC tokens to 'Martin'.  
 
The path in the example graph is invalid because it exceeds the limits for 'Daniels' tokens that are set by 'Martin'. It includes the actual limits for three of the transfers.
![debug_transfer](https://user-images.githubusercontent.com/4954577/203169318-9ff83cad-6f5c-433c-b296-6a18f611a01b.svg)

#### 1) Daniel -[Daniel]-> Martin
'Daniel' sends 505 'Daniel'-CRC directly to 'Martin'.
##### Context
```
tokenOwner := 0xde374ece6fa50e781e81aac78e811b33d16912c7
sender := 0xde374ece6fa50e781e81aac78e811b33d16912c7
dest := 0x42cedde51198d1773590311e2a340dc06b24cb37
```
##### Variables:
```
limit := 50
srcBalance := 1442
destBalance := 0
destsOwnTokenHolding := 1010
```
##### Result:
```
max := 505 = 1010×50÷100
destBalanceScaled := 0 = 0 × (100 - 50) ÷ 100
capacity := 505 = 505 - 0
```

#### 2) Daniel -[Daniel]-> Alte Utting
'Daniel' sends 324 'Daniel'-CRC directly to 'Alte Utting'.  
_'Alte Utting' is an organization and trusts 'Daniel' so 'Daniel' can send all his_ tokens.
#### 3) Daniel -[Daniel]-> 0x0acac72..
'Daniel' sends 324 'Daniel'-CRC directly to '0x0acac72'.  
_'0x0acac72' is an organization and trusts 'Daniel' so 'Daniel' can send all his tokens._
#### 4) Alte Utting -[Daniel]-> Martin
In a second step, the tokens that 'Daniel' previously sent to 'Alte Utting' should be sent to 'Martin'. 'Martin' now already owns 'Daniel ' tokens from step one which influences the capacity.  

_Here is where the example and the actual execution diverge. In the attached example-flow, the attempted transfer amount is higher than the capacity. If we go by the order of this example, then the actual transferable amount is 253 CRC instead of 324 CRC as calculated by the pathfinder._

##### Context
```
tokenOwner := 0xde374ece6fa50e781e81aac78e811b33d16912c7
sender := 0x29335ee3eee0eace4dbc3fc9e2b16be0261ce653
dest := 0x42cedde51198d1773590311e2a340dc06b24cb37
```
##### Variables:
```
limit := 50
srcBalance := 937
destBalance := 505
destsOwnTokenHolding := 1010
```
##### Result:
```
max := 505 = 1010 * 50 / 100  
destBalanceScaled := 252 = 505 * (100 - 50) / 100  
capacity := 253 = 505 - 252
```
#### 5) 0x0acac72.. -[Daniel]-> Martin
In a second step, the tokens that 'Daniel' previously sent to '0x0acac72' should be sent to 'Martin'. 'Martin' now already owns 'Daniel ' tokens from step one and two which influences the capacity.  

_Here is where the example and the actual execution diverge. In the attached example-flow, the attempted transfer amount is higher than the capacity. If we go by the order of this example, then the actual transferable amount is 126 CRC instead of 386 CRC as calculated by the pathfinder._

##### Context
```
tokenOwner := 0xde374ece6fa50e781e81aac78e811b33d16912c7
sender := 0x0acac72e2195695b39721387e5dc0ce70a33c09c
dest := 0x42cedde51198d1773590311e2a340dc06b24cb37
```
##### Variables:
```
limit := 50
srcBalance := 684
destBalance := 758
destsOwnTokenHolding := 1010
```
##### Result:
```
max := 505 = 1010 * 50 / 100  
destBalanceScaled := 379 = 758 * (100 - 50) / 100  
capacity := 126 = 505 - 379  
```
### Appendix
Here is the calldata for the Hub's 'transferTrough' function:
```
From:             0xde374ece6fa50e781e81aac78e811b33d16912c7
Contract address: 0x29b9a7fBb8995b2423a71cC17cf9810798F6C543

0xd62fd9a20000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000022000000000000000000000000000000000000000000000000000000000000003c00000000000000000000000000000000000000000000000000000000000000560000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000249fa3ecd95a53f742707d53688fcafbbd072f3300000000000000000000000092f09a17160b0ed3245d0b82e12452ff12468782000000000000000000000000c7dc64d59e1d2c8b05923bd1da98aa54e3822de7000000000000000000000000de374ece6fa50e781e81aac78e811b33d16912c700000000000000000000000002b50e87c577084b9659a625870b4a6e8a8e923800000000000000000000000070b15a15d71ce5471abb47d4cf414c3000e122540000000000000000000000000142e59d7e0744e984aca46bbe9a7ef5c3fa50ba0000000000000000000000009a0bbbbd3789f184ca88f2f6a40f42406cb842ac000000000000000000000000de374ece6fa50e781e81aac78e811b33d16912c7000000000000000000000000de374ece6fa50e781e81aac78e811b33d16912c7000000000000000000000000de374ece6fa50e781e81aac78e811b33d16912c70000000000000000000000004a9affa9249f36fd0629f342c182a4e94a13c2e0000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000de374ece6fa50e781e81aac78e811b33d16912c7000000000000000000000000de374ece6fa50e781e81aac78e811b33d16912c7000000000000000000000000de374ece6fa50e781e81aac78e811b33d16912c70000000000000000000000000acac72e2195695b39721387e5dc0ce70a33c09c000000000000000000000000de374ece6fa50e781e81aac78e811b33d16912c7000000000000000000000000de374ece6fa50e781e81aac78e811b33d16912c7000000000000000000000000de374ece6fa50e781e81aac78e811b33d16912c7000000000000000000000000de374ece6fa50e781e81aac78e811b33d16912c7000000000000000000000000de374ece6fa50e781e81aac78e811b33d16912c7000000000000000000000000de374ece6fa50e781e81aac78e811b33d16912c700000000000000000000000029335ee3eee0eace4dbc3fc9e2b16be0261ce653000000000000000000000000de374ece6fa50e781e81aac78e811b33d16912c7000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000042cedde51198d1773590311e2a340dc06b24cb3700000000000000000000000042cedde51198d1773590311e2a340dc06b24cb370000000000000000000000000acac72e2195695b39721387e5dc0ce70a33c09c00000000000000000000000042cedde51198d1773590311e2a340dc06b24cb3700000000000000000000000042cedde51198d1773590311e2a340dc06b24cb3700000000000000000000000042cedde51198d1773590311e2a340dc06b24cb3700000000000000000000000042cedde51198d1773590311e2a340dc06b24cb3700000000000000000000000042cedde51198d1773590311e2a340dc06b24cb3700000000000000000000000042cedde51198d1773590311e2a340dc06b24cb3700000000000000000000000029335ee3eee0eace4dbc3fc9e2b16be0261ce65300000000000000000000000042cedde51198d1773590311e2a340dc06b24cb3700000000000000000000000042cedde51198d1773590311e2a340dc06b24cb37000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000001b61c75bdc5fb8ba79000000000000000000000000000000000000000000000014a854e83f8bc5f664000000000000000000000000000000000000000000000014efa2ad202e17ed12000000000000000000000000000000000000000000000014efa2ad202e17ed1200000000000000000000000000000000000000000000001b61c75bdc5fb8ba7900000000000000000000000000000000000000000000000fee6d6cf33c48963800000000000000000000000000000000000000000000001b61c75bdc5fb8ba790000000000000000000000000000000000000000000000149ea2fb835796415300000000000000000000000000000000000000000000001b61c75bdc5fb8ba790000000000000000000000000000000000000000000000119dfa2ac0ae1992df0000000000000000000000000000000000000000000000119dfa2ac0ae1992df00000000000000000000000000000000000000000000001a0620035d17577cbc
```
JSON formatted call arguments:
```
{
  "tokenOwners": [
    "0x249fa3ecd95a53f742707d53688fcafbbd072f33",
    "0x92f09a17160b0ed3245d0b82e12452ff12468782",
    "0xc7dc64d59e1d2c8b05923bd1da98aa54e3822de7",
    "0xde374ece6fa50e781e81aac78e811b33d16912c7",
    "0x02b50e87c577084b9659a625870b4a6e8a8e9238",
    "0x70b15a15d71ce5471abb47d4cf414c3000e12254",
    "0x0142e59d7e0744e984aca46bbe9a7ef5c3fa50ba",
    "0x9a0bbbbd3789f184ca88f2f6a40f42406cb842ac",
    "0xde374ece6fa50e781e81aac78e811b33d16912c7",
    "0xde374ece6fa50e781e81aac78e811b33d16912c7",
    "0xde374ece6fa50e781e81aac78e811b33d16912c7",
    "0x4a9affa9249f36fd0629f342c182a4e94a13c2e0"
  ],
  "srcs": [
    "0xde374ece6fa50e781e81aac78e811b33d16912c7",
    "0xde374ece6fa50e781e81aac78e811b33d16912c7",
    "0xde374ece6fa50e781e81aac78e811b33d16912c7",
    "0x0acac72e2195695b39721387e5dc0ce70a33c09c",
    "0xde374ece6fa50e781e81aac78e811b33d16912c7",
    "0xde374ece6fa50e781e81aac78e811b33d16912c7",
    "0xde374ece6fa50e781e81aac78e811b33d16912c7",
    "0xde374ece6fa50e781e81aac78e811b33d16912c7",
    "0xde374ece6fa50e781e81aac78e811b33d16912c7",
    "0xde374ece6fa50e781e81aac78e811b33d16912c7",
    "0x29335ee3eee0eace4dbc3fc9e2b16be0261ce653",
    "0xde374ece6fa50e781e81aac78e811b33d16912c7"
  ],
  "dests": [
    "0x42cedde51198d1773590311e2a340dc06b24cb37",
    "0x42cedde51198d1773590311e2a340dc06b24cb37",
    "0x0acac72e2195695b39721387e5dc0ce70a33c09c",
    "0x42cedde51198d1773590311e2a340dc06b24cb37",
    "0x42cedde51198d1773590311e2a340dc06b24cb37",
    "0x42cedde51198d1773590311e2a340dc06b24cb37",
    "0x42cedde51198d1773590311e2a340dc06b24cb37",
    "0x42cedde51198d1773590311e2a340dc06b24cb37",
    "0x42cedde51198d1773590311e2a340dc06b24cb37",
    "0x29335ee3eee0eace4dbc3fc9e2b16be0261ce653",
    "0x42cedde51198d1773590311e2a340dc06b24cb37",
    "0x42cedde51198d1773590311e2a340dc06b24cb37"
  ],
  "wads": [
    "505107791134259198585",
    "381064456530232211044",
    "386202435749206813970",
    "386202435749206813970",
    "505107791134259198585",
    "293881669051075827256",
    "505107791134259198585",
    "380365856819939524947",
    "505107791134259198585",
    "324978107268237726431",
    "324978107268237726431",
    "480056702378289102012"
  ]
}
```

**Comment by chriseth** [comment]
Let me try to summarize, please correct me if I'm wrong:

Martin trusts Daniel, that's why he accepts Daniel-tokens. The problem is that the amount of Daniel-tokens Martin can accept through a hub transfer is limited. This limit is global in the sense that it does not matter where these Daniel tokens come from: There is not a capacity limit per channel from a sender, but there is a capacity limit per token.

I could see three ways how we could fix it:

1) We already introduce intermediate nodes for each trust connections that ensure that the same token cannot be spent multiple times (since we use a max flow problem to solve a limited resources problem). We could introduce another intermediate node per token, so that there is only a single incoming arc for each token. This would mean for each trust-arc, there is a "gateway node" before the destination. The capacity of the arc from the gateway node to the final destination is the actual trust limit.
In the example above, the three red arcs going into "Martin" would go into a new node and then there would be a single arc from that new node to Martin.
This way of solving it would limit the transfer to only 505 CRC, I think. This is not the max amount as per the smart contract, but might be how the system was intended.

2) We try to detect such situations and circumvent the send limit. I cannot think this through now, but the hub contract allows arbitrary token transfers given that a) the send limit is not exceeded b) the inputs and outputs sum to zero for each node (except the source and sink). This means we can temporarily move all of Martin's tokens to Martin, which would increase the amount of Daniel-tokens he accepts. After the Daniel-tokens have been transferred, we return the Martin-tokens.

The second solution looks more complicated to me for now and also incurs higher gas costs.

For the first solution, I think we need the pathfinder to compute the edge capacities from the balances and the trust percentages (which is #2 ). If it only has edge capacities, it does not know which edge is a trust transfer and which is a return-own-token edge.

**Comment by jaensen** [comment]
Even if I don't know for sure, I believe it was intended to work like you described in scenario 1.
For me, it sounds like a reasonable approach that gives users a reliable baseline value.

Scenario 2 is very interesting tough and might be useful in scenarios where you really badly want to have the max. capacity between two nodes. But it sounds more like a further optimization on top and also sounds a lot more computationally expensive (in planning and execution of the path).

**Comment by chriseth** [comment]
The second intermediate node has been introduced in https://github.com/chriseth/pathfinder2/commit/f37b35d6ec36b072a287101518335e74b529ae90 . The solution does not yet import from a full database, this is still left to be done.

**Comment by jaensen** [comment]
Hi! I gave it a try and it works now :)
I'd be able to send nearly my whole balance to well connected users.
For further away users, the gas limit is often exceeded but that's expected.
Thx! Closing it.
